import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";

// SEO metadata is rendered by page props -> src/data/seoOverrides.ts ->
// src/components/SeoHead.astro. Do not mutate titles/headings after build;
// doing so makes source metadata differ from deployed HTML.
//
// Sitemaps are generated by the explicit route-registry endpoints under
// src/pages/sitemap.xml.ts and src/pages/sitemaps/*.xml.ts. Do not enable
// @astrojs/sitemap in parallel, because that creates a second sitemap index
// with a different URL surface.
// GH_PAGES_BASE is only ever set by .github/workflows/gh-pages-preview.yml,
// a manually-triggered, non-production preview deploy used while the
// Vercel account's daily deploy quota resets. It must never be set for the
// real Vercel build — leaving it unset here keeps that build unaffected.
const ghPagesBase = process.env.GH_PAGES_BASE;

export default defineConfig({
  site: "https://www.ewastekochi.com",
  ...(ghPagesBase ? { base: ghPagesBase } : {}),
  trailingSlash: "always",
  integrations: [mdx()],
  build: {
    format: "directory",
  },
  server: {
    headers: {
      "X-Content-Type-Options": "nosniff",
      "X-Frame-Options": "DENY",
      "X-XSS-Protection": "1; mode=block",
      "Referrer-Policy": "strict-origin-when-cross-origin",
      "Permissions-Policy": "geolocation=(), microphone=(), camera=()",
      "Content-Security-Policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.whatsapp.com https://wa.me; frame-ancestors 'none';",
    },
  },
});
