import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";

// SEO metadata is rendered by page props -> src/data/seoOverrides.ts ->
// src/components/SeoHead.astro. Do not mutate titles/headings after build;
// doing so makes source metadata differ from deployed HTML.
//
// Sitemaps are generated by the explicit route-registry endpoints under
// src/pages/sitemap.xml.ts and src/pages/sitemaps/*.xml.ts. Do not enable
// @astrojs/sitemap in parallel, because that creates a second sitemap index
// with a different URL surface.
export default defineConfig({
  site: "https://www.ewastekochi.com",
  trailingSlash: "always",
  integrations: [mdx()],
  build: {
    format: "directory",
  },
});
